sacr_tempo_processo_others = '''SELECT DH_PROCESSO, CD_TIPO_TEMPO_PROCESSO, CD_ATENDIMENTO, NM_USUARIO FROM DBAMV.VW_EXIMIO_SACR_TEMPO_PROCESSO WHERE DH_PROCESSO >= TO_DATE('{data_ini}', 'DD/MM/YYYY') AND DH_PROCESSO < TO_DATE('{data_fim}', 'DD/MM/YYYY') + INTERVAL '1' DAY AND CD_TIPO_TEMPO_PROCESSO IN (30,20,32,99,50)'''

