query_atendime_hdata = 'SELECT A.CD_MULTI_EMPRESA, CD_PACIENTE, CD_ATENDIMENTO, CD_CID, CD_MOT_ALT, CD_TIP_RES, CD_CONVENIO, CD_ESPECIALID, CD_PRESTADOR, CD_ATENDIMENTO_PAI, CD_LEITO, A.CD_ORI_ATE, CD_SERVICO, TP_ATENDIMENTO, DT_ATENDIMENTO, HR_ATENDIMENTO, HR_ALTA, HR_ALTA_MEDICA, CD_TIP_MAR, CD_SINTOMA_AVALIACAO, NM_USUARIO_ALTA_MEDICA FROM DBAMV.ATENDIME A'

query_cid_hdata = 'SELECT CD_CID, DS_CID, CD_SGRU_CID FROM DBAMV.CID'

query_classificacao_risco_hdata = 'SELECT CD_CLASSIFICACAO_RISCO, CD_COR_REFERENCIA, CD_TRIAGEM_ATENDIMENTO, DH_CLASSIFICACAO_RISCO FROM DBAMV.SACR_CLASS_RISCO'

query_classificacao_hdata = 'SELECT CD_CLASSIFICACAO, DS_TIPO_RISCO FROM DBAMV.SACR_CLASSIFICACAO'

query_convenio_hdata = 'SELECT CD_CONVENIO, NM_CONVENIO FROM DBAMV.CONVENIO'

query_cor_referencia_hdata = 'SELECT CD_COR_REFERENCIA FROM DBAMV.SACR_COR_REFERENCIA'

query_diagnostico_atendime_hdata = 'SELECT CD_CID, CD_DIAGNOSTICO_ATENDIME, CD_ATENDIMENTO FROM DBAMV.DIAGNOSTICO_ATENDIME'

query_documento_clinico_hdata = "SELECT CD_OBJETO, cd_atendimento, cd_tipo_documento, tp_status, DH_CRIACAO FROM DBAMV.PW_DOCUMENTO_CLINICO"

query_esp_med_hdata = 'SELECT CD_ESPECIALID, CD_PRESTADOR, SN_ESPECIAL_PRINCIPAL FROM DBAMV.ESP_MED'

query_especialidad_hdata = 'SELECT CD_ESPECIALID, DS_ESPECIALID FROM DBAMV.ESPECIALID'

query_gru_cid_hdata = 'SELECT CD_GRU_CID, DS_GRU_CID FROM DBAMV.GRU_CID'

query_mot_alt_hdata = 'SELECT CD_MOT_ALT, DS_MOT_ALT, TP_MOT_ALTA FROM DBAMV.MOT_ALT'

query_multi_empresa_hdata = 'SELECT CD_MULTI_EMPRESA, DS_MULTI_EMPRESA FROM DBAMV.MULTI_EMPRESAS'

query_ori_ate_hdata = 'SELECT CD_ORI_ATE, DS_ORI_ATE, TP_ORIGEM, CD_SETOR FROM DBAMV.ORI_ATE'

query_paciente_hdata = 'SELECT DISTINCT P.CD_PACIENTE, DT_NASCIMENTO, TP_SEXO, DT_CADASTRO, NM_BAIRRO FROM DBAMV.PACIENTE P'

query_pagu_objeto_hdata = 'SELECT CD_OBJETO, TP_OBJETO FROM DBAMV.PAGU_OBJETO'

query_registro_alta_hdata = 'SELECT HR_ALTA_MEDICA, CD_ATENDIMENTO FROM DBAMV.PW_REGISTRO_ALTA'

query_setor_hdata = 'SELECT CD_SETOR, NM_SETOR FROM DBAMV.SETOR'

query_sgru_cid_hdata = 'SELECT CD_SGRU_CID, CD_GRU_CID, DS_SGRU_CID FROM DBAMV.SGRU_CID'

query_sintoma_avaliacao_hdata = 'SELECT CD_SINTOMA_AVALIACAO, DS_SINTOMA FROM DBAMV.SACR_SINTOMA_AV'

query_tempo_processo_hdata = 'SELECT DH_PROCESSO,  CD_TIPO_TEMPO_PROCESSO,  CD_ATENDIMENTO FROM DBAMV.SACR_TEMPO_PROCESSO'

query_tip_mar_hdata = 'SELECT CD_TIP_MAR FROM DBAMV.TIP_MAR'

query_tip_res_hdata = 'SELECT CD_TIP_RES, DS_TIP_RES, SN_OBITO FROM DBAMV.TIP_RES'

query_triagem_atendimento_hdata = 'SELECT CD_ATENDIMENTO, CD_TRIAGEM_ATENDIMENTO, CD_SINTOMA_AVALIACAO, DS_SENHA, DH_PRE_ATENDIMENTO FROM DBAMV.TRIAGEM_ATENDIMENTO'

query_usuario_hdata = 'SELECT CD_USUARIO, NM_USUARIO FROM DBAMV.USUARIOS'

query_pre_med_hdata = 'SELECT CD_PRE_MED, PM.CD_ATENDIMENTO, PM.CD_PRESTADOR, CD_DOCUMENTO_CLINICO, DT_PRE_MED, TP_PRE_MED, PM.CD_SETOR FROM DBAMV.PRE_MED PM'

query_itpre_med_hdata = 'SELECT IP.CD_PRE_MED, CD_ITPRE_MED, CD_PRODUTO, CD_TIP_PRESC, CD_TIP_ESQ, CD_FOR_APL, CD_TIP_FRE, TP_JUSTIFICATIVA FROM DBAMV.ITPRE_MED IP'

query_tip_presc_hdata = 'SELECT TP.CD_TIP_PRESC, DS_TIP_PRESC, CD_PRO_FAT FROM DBAMV.TIP_PRESC TP'

query_for_apl_hdata = 'SELECT CD_FOR_APL, DS_FOR_APL FROM DBAMV.FOR_APL'

query_tip_esq_hdata = 'SELECT CD_TIP_ESQ, DS_TIP_ESQ FROM DBAMV.TIP_ESQ'

query_tip_fre_hdata = 'SELECT CD_TIP_FRE, DS_TIP_FRE FROM DBAMV.TIP_FRE'

query_de_para_tuss_hdata = 'SELECT CNHPM_5, CBHPM_4, CNHPM_3, AMB_1990, AMB_1992, AMB_1996, AMB_1999, TUSS FROM DBAMV.DE_PARA_TUSS'

query_gru_fat_hdata = 'SELECT CD_GRU_FAT, DS_GRU_FAT, TP_GRU_FAT FROM DBAMV.GRU_FAT'

query_gru_pro_hdata = 'SELECT CD_GRU_PRO, CD_GRU_FAT, DS_GRU_PRO, TP_GRU_PRO, TP_CUSTO FROM DBAMV.GRU_PRO'

query_produto_hdata = 'SELECT CD_PRO_FAT, DS_PRODUTO, CD_PRODUTO, VL_FATOR_PRO_FAT, SN_OPME, CD_ESPECIE, VL_CUSTO_MEDIO FROM DBAMV.PRODUTO'

query_pro_fat_hdata = 'SELECT CD_GRU_PRO, CD_PRO_FAT, CD_POR_ANE, DS_PRO_FAT FROM DBAMV.PRO_FAT'

query_tuss_hdata = 'SELECT CD_PRO_FAT, CD_TUSS, DS_TUSS FROM DBAMV.TUSS'

query_uni_pro_hdata = 'SELECT CD_UNIDADE, DS_UNIDADE, VL_FATOR, TP_RELATORIOS, CD_UNI_PRO, CD_PRODUTO, SN_ATIVO FROM DBAMV.UNI_PRO'

query_reg_amb_hdata = 'SELECT DISTINCT RA.CD_REG_AMB, CD_REMESSA, RA.VL_TOTAL_CONTA FROM DBAMV.REG_AMB RA'

query_itreg_amb_hdata = 'SELECT IRA.CD_ATENDIMENTO, CD_PRO_FAT, CD_REG_AMB, CD_GRU_FAT, CD_LANCAMENTO, QT_LANCAMENTO, VL_UNITARIO, VL_NOTA, IRA.CD_SETOR, CD_SETOR_PRODUZIU, TP_PAGAMENTO, SN_PERTENCE_PACOTE, VL_TOTAL_CONTA, SN_FECHADA, DT_FECHAMENTO, CD_ITMVTO FROM DBAMV.ITREG_AMB IRA'

query_reg_fat_hdata = 'SELECT CD_REG_FAT, SN_FECHADA, DT_INICIO, DT_FINAL, DT_FECHAMENTO, CD_REMESSA, VL_TOTAL_CONTA, RF.CD_ATENDIMENTO FROM DBAMV.REG_FAT RF'

query_itreg_fat_hdata = 'SELECT IRF.CD_REG_FAT, CD_LANCAMENTO, DT_LANCAMENTO, QT_LANCAMENTO, TP_PAGAMENTO, VL_UNITARIO, VL_NOTA, IRF.CD_CONTA_PAI, CD_PRO_FAT, CD_GRU_FAT, IRF.VL_TOTAL_CONTA, SN_PERTENCE_PACOTE, IRF.CD_SETOR, CD_SETOR_PRODUZIU, CD_ITMVTO FROM DBAMV.ITREG_FAT IRF'

query_custo_final_hdata = 'SELECT VL_CUSTO_CENCIR, DT_COMPETENCIA FROM DBAMV.CUSTO_FINAL'

query_mvto_estoque_hdata = 'SELECT CD_MVTO_ESTOQUE, ME.CD_SETOR, ME.CD_ATENDIMENTO, CD_MOT_DEV, ME.CD_MULTI_EMPRESA, DT_MVTO_ESTOQUE FROM DBAMV.MVTO_ESTOQUE ME'

query_itmvto_estoque_hdata = 'SELECT CD_ITMVTO_ESTOQUE, QT_MOVIMENTACAO, IME.CD_MVTO_ESTOQUE, CD_PRODUTO, IME.CD_UNI_PRO FROM DBAMV.ITMVTO_ESTOQUE IME'

query_quantidade_diarias_hdata = 'SELECT QD.CD_ATENDIMENTO, VL_DIARIA, QTD_DIARIAS FROM DBAMV.QUANTIDADE_DIARIAS QD'

query_remessa_fatura_hdata = 'SELECT RF.CD_REMESSA, DT_ABERTURA, RF.DT_FECHAMENTO, DT_ENTREGA_DA_FATURA FROM DBAMV.REMESSA_FATURA RF'

query_repasse_hdata = 'SELECT DISTINCT R.CD_REPASSE, DT_COMPETENCIA FROM DBAMV.REPASSE R'

query_it_repasse_hdata = 'SELECT DISTINCT ITR.CD_REG_FAT, CD_LANCAMENTO_FAT, CD_REPASSE FROM DBAMV.IT_REPASSE ITR'

query_itent_pro_hdata = 'SELECT VL_TOTAL, ITP.CD_ATENDIMENTO, CD_PRODUTO, VL_UNITARIO, DT_GRAVACAO FROM DBAMV.ITENT_PRO ITP'

query_glosas_hdata = 'SELECT DISTINCT CD_GLOSAS, CD_REG_FAT, G.CD_REG_AMB, G.CD_MOTIVO_GLOSA, VL_GLOSA, CD_LANCAMENTO_FAT, CD_LANCAMENTO_AMB FROM DBAMV.GLOSAS G'

query_custo_medio_mensal_hdata = 'SELECT VL_CUSTO_MEDIO, DH_CUSTO_MEDIO, CD_PRODUTO, CD_MULTI_EMPRESA FROM DBAMV.CUSTO_MEDIO_MENSAL'

query_fa_custo_atendimento_hdata = 'SELECT VL_DIARIA, VL_CUSTO_GASES, VL_CUSTO_REPASSE, VL_CUSTO_MEDICAMENTO, VL_PROCEDIMENTO, VL_CUSTO_DIARIATAXA, FCA.CD_ATENDIMENTO FROM DBAMV.FA_CUSTO_ATENDIMENTO FCA'

query_especie_hdata = 'SELECT CD_ESPECIE, DS_ESPECIE FROM DBAMV.ESPECIE'

query_exa_lab_hdata = 'SELECT CD_PRO_FAT, CD_EXA_LAB, NM_EXA_LAB FROM DBAMV.EXA_LAB'

query_exa_rx_hdata = 'SELECT EXA_RX_CD_PRO_FAT, CD_EXA_RX, DS_EXA_RX FROM DBAMV.EXA_RX'

query_gru_fat_hdata = 'SELECT CD_GRU_FAT, DS_GRU_FAT, TP_GRU_FAT FROM DBAMV.GRU_FAT'

query_gru_pro_hdata = 'SELECT CD_GRU_PRO, CD_GRU_FAT, DS_GRU_PRO, TP_GRU_PRO, TP_CUSTO FROM DBAMV.GRU_PRO'

query_motivo_glosa_hdata = 'SELECT DS_MOTIVO_GLOSA, CD_MOTIVO_GLOSA FROM DBAMV.MOTIVO_GLOSA'

query_mot_dev_hdata = 'SELECT CD_MOT_DEV, DS_MOT_DEV FROM DBAMV.MOT_DEV'